quarkus.application.name=TAPServer

# registry/resource related
ivoa.baseAddress=http://localhost:8080/
ivoa.registry.authority=authority.changeme
ivoa.dc.organizationName=Organization
ivoa.dc.contactName=Contact Name
ivoa.dc.contactAddress=Contact Address
ivoa.dc.contactEmail=Contact E-mail.
ivoa.dc.contactTelephone=Contact Telephone number

#name of the resource containing the TAP schema XML definition, which must be on the classpath
ivoa.tap.schema=DemoDM.vo-dml.tap.xml
# is the underlying database case sensitive
ivoa.tap.dbCaseSensitive=true
# the timeout for the TAP sync endpoint, in seconds. If the query takes longer than this the server will timeout with an error VOTable response,
# which will contain a reference to the underlying UWS Job which can be queried for the results when they are ready.
# This is to prevent the server from being overloaded by long-running sync queries.
ivoa.tap.sync-timeout-seconds=5

quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.enabled=true
#fix port
%dev.quarkus.datasource.devservices.port=54771
quarkus.datasource.devservices.image-name=images.dev.uksrc.org/library/postgres-pgsphere14:latest
#quarkus.datasource.devservices.image-name=postgis/postgis:14-3.5
#
# PGSphere
quarkus.hibernate-orm.dialect=org.javastro.ivoacore.pgsphere.PgSphereDialect


#ORM setup - mainly for the TAPSchema
quarkus.hibernate-orm.packages=org.ivoa.dm,org.ivoa.vodml.stdtypes,org.javastro.ivoa.tap.entities,org.javastro.ivoacore.uws.persist
#%dev,%test.quarkus.hibernate-orm.database.generation=drop-and-create
%prod.quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.database.generation.create-schemas=true
quarkus.hibernate-orm.database.generation.halt-on-error=false
quarkus.hibernate-orm.quote-identifiers.strategy = all

# below is new quarkus
#quarkus.hibernate-orm.schema-management.strategy=drop-and-create
# older quarkus
quarkus.hibernate-orm.scripts.generation=drop-and-create
quarkus.hibernate-orm.scripts.generation.create-target=TAPddl.sql
quarkus.hibernate-orm.scripts.generation.drop-target=TAP_drop_ddl.sql

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true


#image build
quarkus.container-image.builder=docker
quarkus.container-image.name=tap-server
quarkus.container-image.group=javastro
quarkus.container-image.tag=latest

#Kubernetes/helm
quarkus.kubernetes.image-pull-policy=if-not-present
%prod.quarkus.kubernetes.image-pull-policy=Always
quarkus.helm.description=MVP Tap Server
#FIXME probably do not need ingress in general.
quarkus.kubernetes.ingress.expose=true
quarkus.kubernetes.ingress.path=/tap/*
quarkus.kubernetes.ingress.path-type=Prefix

#force bean scan of ivoa entities
#quarkus.index-dependency.ivoaent.group-id=org.javastro.ivoa
#quarkus.index-dependency.ivoaent.artifact-id=ivoa-entities
